### ISSUE TITLE
Tinker names all over the place - 1.18.2

### ISSUE THREAD

**Issue by ghost** [Jamesdsj/TinkersCalibration#3]
Hello! I am presenting an issue for Tinker's Calibration for 1.18.2 and my issues are:

1.  some bucketed liquids are in another language entirely
2. Items, modifiers, blocks, etc with the long name convention and no description.

![Bucketed liquid with other language name](https://github.com/user-attachments/assets/0ac27204-f83e-4663-9919-b56a8022a0a7)
![Tag in name](https://github.com/user-attachments/assets/22bc2944-046b-4b5c-a7e5-73daa7002254)
![2024-10-26_10 38 49](https://github.com/user-attachments/assets/7c52e3a4-b174-49d4-bdf5-31051a4f8c48)
![2024-10-26_10 22 45](https://github.com/user-attachments/assets/d859f092-fcd6-4909-ba21-e53bf2d93023)

**Comment by Jamesdsj** [comment]
These are Chinese. I don't have much time to write these names in English. The en_us language file hasn't been updated since 1.0.2.
I may use AI to translate them, but I can't guarantee the quality.
Sorry for the inconvenience and thank you for trying my mod!

**Comment by Jamesdsj** [comment]
I'm translating them now. It's quite fast using AI.

**Comment by Jamesdsj** [comment]
All right, now you can play the new version.

**Comment by ghost** [comment]
Alright, although I don't see it on forge yet, I can't wait to see the names, oh and what about the item names and skill descriptions?

**Comment by Jamesdsj** [comment]
It's on github. You'll see it on Curseforge soon.

**Comment by Jamesdsj** [comment]
Sorry for late response. It was 1 a.m. when I submit the new version because I'm in China. After that, I went to bed.
